################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
gecko_sdk_3.2.3/app/bluetooth/common/simple_timer \
gecko_sdk_3.2.3/app/homekit/common/ota_dfu \
gecko_sdk_3.2.3/hardware/board/src \
gecko_sdk_3.2.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_3.2.3/platform/Device/SiliconLabs/MGM12/Source/GCC \
gecko_sdk_3.2.3/platform/Device/SiliconLabs/MGM12/Source \
gecko_sdk_3.2.3/platform/bootloader/api \
gecko_sdk_3.2.3/platform/common/src \
gecko_sdk_3.2.3/platform/common/toolchain/src \
gecko_sdk_3.2.3/platform/driver/button/src \
gecko_sdk_3.2.3/platform/driver/leddrv/src \
gecko_sdk_3.2.3/platform/emdrv/dmadrv/src \
gecko_sdk_3.2.3/platform/emdrv/gpiointerrupt/src \
gecko_sdk_3.2.3/platform/emdrv/nvm3/src \
gecko_sdk_3.2.3/platform/emdrv/uartdrv/src \
gecko_sdk_3.2.3/platform/emdrv/ustimer/src \
gecko_sdk_3.2.3/platform/emlib/src \
gecko_sdk_3.2.3/platform/radio/rail_lib/plugin/fem_util \
gecko_sdk_3.2.3/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_3.2.3/platform/service/device_init/src \
gecko_sdk_3.2.3/platform/service/mpu/src \
gecko_sdk_3.2.3/platform/service/power_manager/src \
gecko_sdk_3.2.3/platform/service/sleeptimer/src \
gecko_sdk_3.2.3/platform/service/system/src \
gecko_sdk_3.2.3/platform/service/udelay/src \
gecko_sdk_3.2.3/protocol/bluetooth/lib/EFR32MG12P/GCC \
gecko_sdk_3.2.3/protocol/bluetooth/src \
gecko_sdk_3.2.3/protocol/openthread/platform-abstraction/efr32 \
gecko_sdk_3.2.3/protocol/openthread/src/cli \
gecko_sdk_3.2.3/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_3.2.3/util/third_party/crypto/mbedtls/library \
gecko_sdk_3.2.3/util/third_party/crypto/sl_component/sl_alt/source \
gecko_sdk_3.2.3/util/third_party/crypto/sl_component/sl_mbedtls_support/src \
gecko_sdk_3.2.3/util/third_party/crypto/sl_component/sl_protocol_crypto/src \
gecko_sdk_3.2.3/util/third_party/crypto/sl_component/sl_psa_driver/src \
gecko_sdk_3.2.3/util/third_party/homekit/Applications \
gecko_sdk_3.2.3/util/third_party/homekit/Applications/Common/Helper \
gecko_sdk_3.2.3/util/third_party/homekit/Applications/Common/Platform \
gecko_sdk_3.2.3/util/third_party/homekit/Applications/Common/Platform/SiliconLabs \
gecko_sdk_3.2.3/util/third_party/homekit/Applications/Lightbulb \
gecko_sdk_3.2.3/util/third_party/homekit/External/Base64 \
gecko_sdk_3.2.3/util/third_party/homekit/External/mdnsresponder/ServiceRegistration \
gecko_sdk_3.2.3/util/third_party/homekit/External/mdnsresponder/mDNSShared \
gecko_sdk_3.2.3/util/third_party/homekit/HAP \
gecko_sdk_3.2.3/util/third_party/homekit/HAP/Thread \
gecko_sdk_3.2.3/util/third_party/homekit/PAL \
gecko_sdk_3.2.3/util/third_party/homekit/PAL/SiliconLabs/Crypto/MbedTLSWithPSACrypto \
gecko_sdk_3.2.3/util/third_party/homekit/PAL/SiliconLabs \
gecko_sdk_3.2.3/util/third_party/homekit/PAL/Thread/OpenThread \
gecko_sdk_3.2.3/util/third_party/openthread/examples/apps/cli \
gecko_sdk_3.2.3/util/third_party/openthread/examples/platforms/utils \
gecko_sdk_3.2.3/util/third_party/openthread/src/cli \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/api \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/backbone_router \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/border_router \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/coap \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/common \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/coprocessor \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/crypto \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/diags \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/mac \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/meshcop \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/net \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/radio \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/thread \
gecko_sdk_3.2.3/util/third_party/openthread/src/core/utils \
gecko_sdk_3.2.3/util/third_party/segger/systemview/SEGGER \

